server:
  port: 8760
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DongQi123456/dq-springcloud-parent.git
          username: DongQi123456
          password: Dongqi343668
          search-paths: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   #将自己的IP注册到Eureka Server
security:
  basic:
    #开启基于Http basic的认证
    enabled: true
  user:
    name: user
    password: password123