server:
  port: 8081
#spring:
#  application:
#    name: dq-consumer-movie-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true   #将自己的IP注册到Eureka Server

user:
  userServiceUrl: http://localhost:8080/

# 默认之配置为TM的本机默认端口
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
#  tx-lcn.client.manager-address=127.0.0.1:8070