server:
  port: 8092

spring:
  application:
    name: dq-security-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/user_management
    username: root
    password: root123

    #hikari 数据源配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
eureka:
  client:
    service-url:
      defaultZone: http://@application.server.ip@:@eureka.application.port@/eureka/
  instance:
    prefer-ip-address: true   #将自己的IP注册到Eureka Server
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.po